---
- name: Ansible Deployment
  hosts:
    - atlanta
    - raleigh

  vars_files:
    - secrets.yml

  roles:
    - install_packages

  tasks:
    - name: Get hostname
      debug:
        msg: '{{ ansible_hostname }}'
      tags:
        - debug