---
- name: Run web server using Podman
  hosts: all

  tasks:
    - name: Install Podman and related tools
      ansible.builtin.dnf:
        name: 'container-tools:ol8'
        state: present
        