---
- name: Run web server using Podman
  hosts: all

  tasks:
    - name: Install Podman and related tools
      ansible.builtin.dnf:
        name: '@container-tools:ol8'
        state: present
      become: yes

    - name: Run NGINX container image
      containers.podman.podman_container:
        name: my-ol8
        image: ghcr.io/oracle/oraclelinux8-nginx:1.18
        state: started
        detach: yes
        expose:
          - '80'
          - '443'
        publish:
          - '8080:80'

    - name: Ensure firewalld is enabled and started
      ansible.builtin.systemd:
        name: firewalld
        state: started
        enabled: true
      become: yes

    - name: Allow web traffic on port 8080
      ansible.posix.firewalld:
        port: 8080/tcp
        permanent: true
        state: enabled
      become: yes