- name: "Add inventory for each location"
  awx.awx.inventory:
    name: "{{ item.name }}"
    description: "Computers in {{ item.name }}"
    organization: "Default"
    state: present
  loop: "{{ vars.inventory }}"

- name: Add an inventory source for each location
  awx.awx.inventory_source:
    name: "hosts"
    description: Source for inventory
    inventory: "{{ item.name }}"
    source: "scm"
    source_project: "{{ project_name }}"
    source_path: "hosts"
    host_filter: "{{ item.host_filter }}"
    overwrite: True
    update_on_launch: True
    organization: Default
  loop: "{{ vars.inventory }}"

- name: Update inventory source for each location
  awx.awx.inventory_source_update:
    name: "hosts"
    inventory: "{{ item.name }}"
  loop: "{{ vars.inventory }}"